### ISSUE TITLE
Go 1.12b - Memory allocation fails after reconstruction

### ISSUE THREAD

**Issue by jerrinsg** [jerrinsg/go-pmem#20]
With the 1.12b branch, pmem memory allocations performed after heap recovery are seen to be failing with the following error message:

```
Not a first time intialization
fatal error: candidate mspan for allocation is not free

runtime stack:
runtime.throw(0x5228a1, 0x2a)
	/home/jerrin/go-pmem/src/runtime/panic.go:617 +0x72
runtime.(*mheap).allocSpanLocked(0x646b40, 0x1, 0x71dba8, 0x1, 0x7f5f192c9b90)
	/home/jerrin/go-pmem/src/runtime/mheap.go:1204 +0x4a5
runtime.(*mheap).alloc_m(0x646b40, 0x1, 0xc000140008, 0x1, 0x7f5f192c9b90)
	/home/jerrin/go-pmem/src/runtime/mheap.go:1010 +0xcc
runtime.(*mheap).alloc.func1()
	/home/jerrin/go-pmem/src/runtime/mheap.go:1084 +0x55
runtime.systemstack(0x45c989)
	/home/jerrin/go-pmem/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/home/jerrin/go-pmem/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/jerrin/go-pmem/src/runtime/asm_amd64.s:311 fp=0xc000140bf0 sp=0xc000140be8 pc=0x45ca80
runtime.(*mheap).alloc(0x646b40, 0x1, 0x10008, 0x1, 0x20)
	/home/jerrin/go-pmem/src/runtime/mheap.go:1083 +0x90 fp=0xc000140c48 sp=0xc000140bf0 pc=0x427980
runtime.(*mcentral).grow(0x6b8150, 0x1, 0x20300000000000)
	/home/jerrin/go-pmem/src/runtime/mcentral.go:260 +0x9f fp=0xc000140c98 sp=0xc000140c48 pc=0x41a74f
runtime.(*mcentral).cacheSpan(0x6b8150, 0x1, 0xc00642a000)
	/home/jerrin/go-pmem/src/runtime/mcentral.go:108 +0x2fa fp=0xc000140cf8 sp=0xc000140c98 pc=0x41a25a
runtime.(*mcache).refill(0x7f5f19ea1000, 0x8, 0x1)
	/home/jerrin/go-pmem/src/runtime/mcache.go:156 +0xe1 fp=0xc000140d38 sp=0xc000140cf8 pc=0x419bd1
runtime.(*mcache).nextFree(0x7f5f19ea1000, 0x8, 0x1, 0x4dca92, 0xc000140dc0, 0xc000140f20)
	/home/jerrin/go-pmem/src/runtime/malloc.go:819 +0xcd fp=0xc000140d88 sp=0xc000140d38 pc=0x40e9cd
runtime.mallocgc(0x30, 0x506460, 0x7f5f19ea1001, 0x1, 0x0)
	/home/jerrin/go-pmem/src/runtime/malloc.go:1004 +0x9dc fp=0xc000140e50 sp=0xc000140d88 pc=0x40f55c
runtime.pnewobject(0x506460, 0x7f5f192a0000)
	/home/jerrin/go-pmem/src/runtime/malloc.go:1172 +0x41 fp=0xc000140e88 sp=0xc000140e50 pc=0x40fab1
main.addNode(0xc00642c000)
	/home/jerrin/gocode/src/github.com/vmware/go-pmem-transaction/examples/database.go:63 +0x3f fp=0xc000140f30 sp=0xc000140e88 pc=0x4d7b9f
main.main()
	/home/jerrin/gocode/src/github.com/vmware/go-pmem-transaction/examples/database.go:108 +0x1ac fp=0xc000140f98 sp=0xc000140f30 pc=0x4d81fc
runtime.main()
	/home/jerrin/go-pmem/src/runtime/proc.go:200 +0x20c fp=0xc000140fe0 sp=0xc000140f98 pc=0x4364dc
runtime.goexit()
	/home/jerrin/go-pmem/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000140fe8 sp=0xc000140fe0 pc=0x45e9d1
```

**Comment by jerrinsg** [comment]
Closing this issue as go-pmem is being ported to the 1.15 codebase.
